version: '3'

services:
 mongo:
  image: mongo:4.4.0
  ports:
    - 27017:27017
  volumes:
    - ./infrastructure/mongo:/data

 redis:
  image: redis:6.0.6
  ports:
    - 6379:6379
  volumes:
    - ./infrastructure/redis
